export default {
  "index": "Startseite",
  "erste-schritte": "Erste Schritte",
  "materialien": "Materialien",
  "werkzeuge": "Werkzeuge",
  "standorte": "Standorte",
  "lieferscheine": "Lieferscheine",
  "inventur": "Inventur",
  "rueckverfolgung": "Rückverfolgung",
  "finanzen": "Finanzen",
  "ai": "KI-Funktionen",
  "automatisierung": "Automatisierung",
  "erweitert": "Erweiterte Funktionen",
  "hardware": "Hardware & Peripherie",
  "mobile-app": "Mobile App",
  "einstellungen": "Einstellungen",
  "berichte": "Berichte & Analytik",
  "api-docs": "API-Dokumentation",
  "sicherheit": "Sicherheit & Datenschutz",
  "faq": "Häufige Fragen",
  "changelog": "Changelog"
}
