import type { Session } from "../session-store";
import type {
  DashboardStats,
  ScanResult,
  Commission,
  CommissionEntry,
  TimeEntry,
  DeliveryTracking,
  WarrantyClaim,
  Geofence,
  GeofenceEvent,
  BleBeacon,
} from "../api-types";

// ── Session ──────────────────────────────────────────────────────────────────

export const DEMO_SESSION: Session = {
  user: {
    id: "demo-user-123",
    email: "demo@logistikapp.ch",
    name: "Max Muster",
    role: "user",
    image: null,
  },
  token: "demo-token-xxx",
};

// ── Org ───────────────────────────────────────────────────────────────────────

export const DEMO_ORG_ID = "demo-org-456";

// ── Dashboard Stats ───────────────────────────────────────────────────────────

export const DEMO_DASHBOARD_STATS: DashboardStats = {
  materials: 148,
  tools: 37,
  keys: 12,
  users: 5,
  maxUsers: 10,
  lowStockCount: 3,
  expiringCount: 2,
  overdueToolsCount: 1,
  activeTimerMinutes: 45,
  pendingDeliveries: 3,
  openWarrantyClaims: 2,
};

// ── Commissions ───────────────────────────────────────────────────────────────

export const DEMO_COMMISSIONS: Commission[] = [
  {
    id: "commission-001",
    name: "Baustelle Zürich Altstetten",
    number: 1001,
    manualNumber: "BS-2024-001",
    status: "in_progress",
    notes: "Rohbau EG fertigstellen bis Ende Woche",
    targetLocationId: "loc-001",
    targetLocationName: "Lager Zürich",
    customerId: "cust-001",
    customerName: "Baugenossenschaft Altstetten",
    responsibleId: "demo-user-123",
    responsibleName: "Max Muster",
    entryCount: 4,
    createdAt: "2024-02-01T08:00:00.000Z",
    updatedAt: "2024-03-10T14:30:00.000Z",
  },
  {
    id: "commission-002",
    name: "Renovation Bern Matte",
    number: 1002,
    manualNumber: "BS-2024-002",
    status: "open",
    notes: "Fassadensanierung, Material noch zu bestellen",
    targetLocationId: "loc-002",
    targetLocationName: "Lager Bern",
    customerId: "cust-002",
    customerName: "Liegenschaftsverwaltung Matte AG",
    responsibleId: "demo-user-123",
    responsibleName: "Max Muster",
    entryCount: 2,
    createdAt: "2024-02-15T09:00:00.000Z",
    updatedAt: "2024-03-12T11:00:00.000Z",
  },
  {
    id: "commission-003",
    name: "Lager Winterthur",
    number: 1003,
    manualNumber: "BS-2024-003",
    status: "open",
    notes: null,
    targetLocationId: "loc-003",
    targetLocationName: "Lager Winterthur",
    customerId: "cust-003",
    customerName: "Winterthur Industrie AG",
    responsibleId: null,
    responsibleName: null,
    entryCount: 3,
    createdAt: "2024-03-01T07:30:00.000Z",
    updatedAt: "2024-03-14T16:00:00.000Z",
  },
  {
    id: "commission-004",
    name: "Umbau Basel Kleinbasel",
    number: 1004,
    manualNumber: "BS-2024-004",
    status: "completed",
    notes: "Abgeschlossen, alle Materialien retourniert",
    targetLocationId: "loc-004",
    targetLocationName: "Lager Basel",
    customerId: "cust-004",
    customerName: "Immobilien Basel GmbH",
    responsibleId: "demo-user-123",
    responsibleName: "Max Muster",
    entryCount: 5,
    createdAt: "2024-01-10T08:00:00.000Z",
    updatedAt: "2024-02-28T17:00:00.000Z",
  },
  {
    id: "commission-005",
    name: "Montage Luzern Tribschen",
    number: 1005,
    manualNumber: "BS-2024-005",
    status: "in_progress",
    notes: "Elektroinstallation 2. OG läuft",
    targetLocationId: "loc-005",
    targetLocationName: "Lager Luzern",
    customerId: "cust-005",
    customerName: "Wohnbau Tribschen AG",
    responsibleId: "demo-user-123",
    responsibleName: "Max Muster",
    entryCount: 3,
    createdAt: "2024-03-05T09:00:00.000Z",
    updatedAt: "2024-03-17T10:15:00.000Z",
  },
];

// ── Commission Entries ────────────────────────────────────────────────────────

export const DEMO_COMMISSION_ENTRIES: Record<string, CommissionEntry[]> = {
  "commission-001": [
    {
      id: "entry-001-1",
      commissionId: "commission-001",
      materialId: "mat-001",
      materialName: "Zement CEM II 42.5",
      materialNumber: "ZEM-001",
      materialUnit: "Sack",
      toolId: null,
      toolName: null,
      toolNumber: null,
      quantity: 50,
      pickedQuantity: 50,
      status: "picked",
      notes: null,
      createdAt: "2024-02-01T08:30:00.000Z",
    },
    {
      id: "entry-001-2",
      commissionId: "commission-001",
      materialId: "mat-002",
      materialName: "Armierungseisen 10mm",
      materialNumber: "ARM-010",
      materialUnit: "Stk",
      toolId: null,
      toolName: null,
      toolNumber: null,
      quantity: 200,
      pickedQuantity: 180,
      status: "partial",
      notes: "20 Stk nachliefern",
      createdAt: "2024-02-01T08:30:00.000Z",
    },
    {
      id: "entry-001-3",
      commissionId: "commission-001",
      materialId: null,
      materialName: null,
      materialNumber: null,
      materialUnit: null,
      toolId: "tool-001",
      toolName: "Bohrhammer Hilti TE 70",
      toolNumber: "WZ-0042",
      quantity: 1,
      pickedQuantity: 1,
      status: "picked",
      notes: null,
      createdAt: "2024-02-02T07:00:00.000Z",
    },
    {
      id: "entry-001-4",
      commissionId: "commission-001",
      materialId: "mat-003",
      materialName: "Schalungsplatte 21mm",
      materialNumber: "SCH-021",
      materialUnit: "m²",
      toolId: null,
      toolName: null,
      toolNumber: null,
      quantity: 80,
      pickedQuantity: 0,
      status: "pending",
      notes: null,
      createdAt: "2024-02-05T09:00:00.000Z",
    },
  ],
  "commission-002": [
    {
      id: "entry-002-1",
      commissionId: "commission-002",
      materialId: "mat-004",
      materialName: "Fassadenfarbe weiss 10L",
      materialNumber: "FAR-WS10",
      materialUnit: "Eimer",
      toolId: null,
      toolName: null,
      toolNumber: null,
      quantity: 20,
      pickedQuantity: 0,
      status: "pending",
      notes: "Bestellt, Lieferung KW 13",
      createdAt: "2024-02-15T09:30:00.000Z",
    },
    {
      id: "entry-002-2",
      commissionId: "commission-002",
      materialId: "mat-005",
      materialName: "Dämmplatten EPS 100mm",
      materialNumber: "DAE-EPS100",
      materialUnit: "m²",
      toolId: null,
      toolName: null,
      toolNumber: null,
      quantity: 120,
      pickedQuantity: 0,
      status: "pending",
      notes: null,
      createdAt: "2024-02-15T09:30:00.000Z",
    },
  ],
  "commission-003": [
    {
      id: "entry-003-1",
      commissionId: "commission-003",
      materialId: "mat-006",
      materialName: "Palettenregal Rahmen 4m",
      materialNumber: "REG-R4",
      materialUnit: "Stk",
      toolId: null,
      toolName: null,
      toolNumber: null,
      quantity: 10,
      pickedQuantity: 10,
      status: "picked",
      notes: null,
      createdAt: "2024-03-01T08:00:00.000Z",
    },
    {
      id: "entry-003-2",
      commissionId: "commission-003",
      materialId: "mat-007",
      materialName: "Regalträger 1200mm",
      materialNumber: "REG-T12",
      materialUnit: "Paar",
      toolId: null,
      toolName: null,
      toolNumber: null,
      quantity: 40,
      pickedQuantity: 40,
      status: "picked",
      notes: null,
      createdAt: "2024-03-01T08:00:00.000Z",
    },
    {
      id: "entry-003-3",
      commissionId: "commission-003",
      materialId: null,
      materialName: null,
      materialNumber: null,
      materialUnit: null,
      toolId: "tool-002",
      toolName: "Gabelstapler Still FM-X",
      toolNumber: "WZ-0018",
      quantity: 1,
      pickedQuantity: 0,
      status: "pending",
      notes: "Noch nicht abgeholt",
      createdAt: "2024-03-02T07:30:00.000Z",
    },
  ],
  "commission-004": [
    {
      id: "entry-004-1",
      commissionId: "commission-004",
      materialId: "mat-008",
      materialName: "Rigipsplatten 12.5mm",
      materialNumber: "RIG-125",
      materialUnit: "Stk",
      toolId: null,
      toolName: null,
      toolNumber: null,
      quantity: 100,
      pickedQuantity: 100,
      status: "picked",
      notes: null,
      createdAt: "2024-01-10T08:30:00.000Z",
    },
    {
      id: "entry-004-2",
      commissionId: "commission-004",
      materialId: "mat-009",
      materialName: "Spachtel Knauf Uniflott 5kg",
      materialNumber: "SPA-KU5",
      materialUnit: "Eimer",
      toolId: null,
      toolName: null,
      toolNumber: null,
      quantity: 15,
      pickedQuantity: 15,
      status: "picked",
      notes: null,
      createdAt: "2024-01-10T08:30:00.000Z",
    },
  ],
  "commission-005": [
    {
      id: "entry-005-1",
      commissionId: "commission-005",
      materialId: "mat-010",
      materialName: "NYM-J Kabel 3x1.5mm²",
      materialNumber: "KAB-NYM315",
      materialUnit: "m",
      toolId: null,
      toolName: null,
      toolNumber: null,
      quantity: 500,
      pickedQuantity: 300,
      status: "partial",
      notes: null,
      createdAt: "2024-03-05T09:30:00.000Z",
    },
    {
      id: "entry-005-2",
      commissionId: "commission-005",
      materialId: "mat-011",
      materialName: "Unterputzdose 68mm",
      materialNumber: "DOS-UP68",
      materialUnit: "Stk",
      toolId: null,
      toolName: null,
      toolNumber: null,
      quantity: 80,
      pickedQuantity: 80,
      status: "picked",
      notes: null,
      createdAt: "2024-03-05T09:30:00.000Z",
    },
    {
      id: "entry-005-3",
      commissionId: "commission-005",
      materialId: null,
      materialName: null,
      materialNumber: null,
      materialUnit: null,
      toolId: "tool-003",
      toolName: "Kabelmessgerät Fluke 1664 FC",
      toolNumber: "WZ-0099",
      quantity: 1,
      pickedQuantity: 1,
      status: "picked",
      notes: null,
      createdAt: "2024-03-06T07:00:00.000Z",
    },
  ],
};

// ── Scan Result ───────────────────────────────────────────────────────────────

// ── Time Entries ─────────────────────────────────────────────────────────────

export const DEMO_TIME_ENTRIES: TimeEntry[] = [
  {
    id: "time-001",
    userId: "demo-user-123",
    userName: "Max Muster",
    commissionId: "commission-001",
    commissionName: "Baustelle Zürich Altstetten",
    projectId: null,
    projectName: null,
    description: "Schalungsarbeiten EG Decke",
    startTime: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    endTime: null,
    durationMinutes: null,
    billable: true,
    hourlyRate: 9500, // CHF 95.00
    status: "running",
  },
  {
    id: "time-002",
    userId: "demo-user-123",
    userName: "Max Muster",
    commissionId: "commission-001",
    commissionName: "Baustelle Zürich Altstetten",
    projectId: null,
    projectName: null,
    description: "Materialannahme und Einlagerung",
    startTime: "2026-03-20T07:00:00.000Z",
    endTime: "2026-03-20T08:30:00.000Z",
    durationMinutes: 90,
    billable: true,
    hourlyRate: 9500,
    status: "stopped",
  },
  {
    id: "time-003",
    userId: "demo-user-123",
    userName: "Max Muster",
    commissionId: "commission-005",
    commissionName: "Montage Luzern Tribschen",
    projectId: null,
    projectName: null,
    description: "Elektroinstallation 2. OG Verteiler",
    startTime: "2026-03-19T08:00:00.000Z",
    endTime: "2026-03-19T12:15:00.000Z",
    durationMinutes: 255,
    billable: true,
    hourlyRate: 12000, // CHF 120.00
    status: "approved",
  },
  {
    id: "time-004",
    userId: "demo-user-123",
    userName: "Max Muster",
    commissionId: null,
    commissionName: null,
    projectId: "proj-001",
    projectName: "Interne Wartung",
    description: "Werkzeugwartung und Inventur",
    startTime: "2026-03-18T13:00:00.000Z",
    endTime: "2026-03-18T15:30:00.000Z",
    durationMinutes: 150,
    billable: false,
    hourlyRate: null,
    status: "stopped",
  },
  {
    id: "time-005",
    userId: "demo-user-123",
    userName: "Max Muster",
    commissionId: "commission-002",
    commissionName: "Renovation Bern Matte",
    projectId: null,
    projectName: null,
    description: "Fassadenvermessung und Aufnahme",
    startTime: "2026-03-17T09:00:00.000Z",
    endTime: "2026-03-17T16:00:00.000Z",
    durationMinutes: 420,
    billable: true,
    hourlyRate: 8500, // CHF 85.00
    status: "approved",
  },
];

// ── Delivery Tracking ────────────────────────────────────────────────────────

export const DEMO_DELIVERIES: DeliveryTracking[] = [
  {
    id: "del-001",
    orderId: "ord-001",
    orderNumber: "PO-2026-0148",
    supplierName: "Hilti Schweiz AG",
    trackingNumber: "99.00.1234.56789012",
    carrier: "Post",
    expectedDeliveryDate: "2026-03-21",
    actualDeliveryDate: null,
    status: "in_transit",
    notes: "Bohrhammer und Zubehör",
    createdAt: "2026-03-17T10:00:00.000Z",
  },
  {
    id: "del-002",
    orderId: "ord-002",
    orderNumber: "PO-2026-0149",
    supplierName: "Sika Schweiz AG",
    trackingNumber: "JJD000390009876543210",
    carrier: "DHL",
    expectedDeliveryDate: "2026-03-20",
    actualDeliveryDate: null,
    status: "shipped",
    notes: "Abdichtungsmaterial Keller",
    createdAt: "2026-03-18T08:00:00.000Z",
  },
  {
    id: "del-003",
    orderId: "ord-003",
    orderNumber: "PO-2026-0145",
    supplierName: "Knauf AG",
    trackingNumber: null,
    carrier: "Planzer",
    expectedDeliveryDate: "2026-03-18",
    actualDeliveryDate: null,
    status: "confirmed",
    notes: "Rigipsplatten 200 Stk — ÜBERFÄLLIG",
    createdAt: "2026-03-14T09:00:00.000Z",
  },
  {
    id: "del-004",
    orderId: "ord-004",
    orderNumber: "PO-2026-0150",
    supplierName: "Würth AG",
    trackingNumber: null,
    carrier: null,
    expectedDeliveryDate: "2026-03-25",
    actualDeliveryDate: null,
    status: "ordered",
    notes: "Befestigungsmaterial Grossbestellung",
    createdAt: "2026-03-19T14:00:00.000Z",
  },
  {
    id: "del-005",
    orderId: "ord-005",
    orderNumber: "PO-2026-0143",
    supplierName: "Weber Saint-Gobain",
    trackingNumber: "01520012345678901",
    carrier: "DPD",
    expectedDeliveryDate: "2026-03-15",
    actualDeliveryDate: "2026-03-15",
    status: "delivered",
    notes: "Bodenausgleichsmasse 50 Sack",
    createdAt: "2026-03-10T11:00:00.000Z",
  },
  {
    id: "del-006",
    orderId: "ord-006",
    orderNumber: "PO-2026-0151",
    supplierName: "Geberit AG",
    trackingNumber: "15001234567890",
    carrier: "Planzer",
    expectedDeliveryDate: "2026-03-22",
    actualDeliveryDate: null,
    status: "in_transit",
    notes: "Sanitärinstallationsmaterial",
    createdAt: "2026-03-19T07:30:00.000Z",
  },
];

// ── Warranty Claims ──────────────────────────────────────────────────────────

export const DEMO_WARRANTY_CLAIMS: WarrantyClaim[] = [
  {
    id: "wc-001",
    claimNumber: "WC-2026-001",
    entityType: "tool",
    entityName: "Bohrhammer Hilti TE 70",
    reason: "Defekter Schlagmechanismus",
    description:
      "Bohrhammer schaltet bei Belastung ab. Gerät ist 8 Monate alt, innerhalb Garantiezeit (2 Jahre).",
    status: "in_review",
    resolution: null,
    submittedAt: "2026-03-12T09:00:00.000Z",
    resolvedAt: null,
    createdAt: "2026-03-11T16:00:00.000Z",
  },
  {
    id: "wc-002",
    claimNumber: "WC-2026-002",
    entityType: "material",
    entityName: "Sika Abdichtungsbahn 1.5mm",
    reason: "Materialfehler — Risse nach Verlegung",
    description:
      "Abdichtungsbahn zeigt nach 3 Wochen Risse. Charge 2025-11. Lieferant informiert.",
    status: "approved",
    resolution: "Kostenlose Ersatzlieferung durch Sika bestätigt.",
    submittedAt: "2026-03-05T10:00:00.000Z",
    resolvedAt: null,
    createdAt: "2026-03-04T14:00:00.000Z",
  },
  {
    id: "wc-003",
    claimNumber: "WC-2026-003",
    entityType: "tool",
    entityName: "Kabelmessgerät Fluke 1664 FC",
    reason: "Display-Ausfall",
    description: "Display flackert und wird nach 5 Minuten schwarz. Gerät 14 Monate alt.",
    status: "submitted",
    resolution: null,
    submittedAt: "2026-03-18T11:00:00.000Z",
    resolvedAt: null,
    createdAt: "2026-03-18T10:30:00.000Z",
  },
  {
    id: "wc-004",
    claimNumber: "WC-2026-004",
    entityType: "material",
    entityName: "Knauf Uniflott Spachtelmasse 5kg",
    reason: "Falsche Konsistenz — ausgehärtet bei Lieferung",
    description: null,
    status: "resolved",
    resolution: "Gutschrift CHF 320.00 erhalten. Charge retourniert.",
    submittedAt: "2026-02-20T08:00:00.000Z",
    resolvedAt: "2026-03-01T14:00:00.000Z",
    createdAt: "2026-02-19T15:00:00.000Z",
  },
];

// ── Geofences ────────────────────────────────────────────────────────────────

export const DEMO_GEOFENCES: Geofence[] = [
  {
    id: "geo-001",
    locationId: "loc-001",
    locationName: "Lager Zürich",
    latitude: "47.3769",
    longitude: "8.5417",
    radiusMeters: 150,
    autoCheckin: true,
    autoCheckout: true,
    isActive: true,
  },
  {
    id: "geo-002",
    locationId: "loc-002",
    locationName: "Lager Bern",
    latitude: "46.9480",
    longitude: "7.4474",
    radiusMeters: 200,
    autoCheckin: true,
    autoCheckout: false,
    isActive: true,
  },
  {
    id: "geo-003",
    locationId: "loc-004",
    locationName: "Lager Basel",
    latitude: "47.5596",
    longitude: "7.5886",
    radiusMeters: 120,
    autoCheckin: true,
    autoCheckout: true,
    isActive: true,
  },
  {
    id: "geo-004",
    locationId: "loc-003",
    locationName: "Lager Winterthur",
    latitude: "47.5001",
    longitude: "8.7240",
    radiusMeters: 180,
    autoCheckin: false,
    autoCheckout: false,
    isActive: false,
  },
];

export const DEMO_GEOFENCE_EVENTS: GeofenceEvent[] = [
  {
    id: "gev-001",
    geofenceId: "geo-001",
    locationName: "Lager Zürich",
    userId: "demo-user-123",
    userName: "Max Muster",
    eventType: "enter",
    triggeredAt: "2026-03-20T06:55:00.000Z",
    autoAction: "checkin",
  },
  {
    id: "gev-002",
    geofenceId: "geo-001",
    locationName: "Lager Zürich",
    userId: "demo-user-123",
    userName: "Max Muster",
    eventType: "exit",
    triggeredAt: "2026-03-20T07:30:00.000Z",
    autoAction: "checkout",
  },
  {
    id: "gev-003",
    geofenceId: "geo-002",
    locationName: "Lager Bern",
    userId: "user-002",
    userName: "Anna Brunner",
    eventType: "enter",
    triggeredAt: "2026-03-20T08:10:00.000Z",
    autoAction: "checkin",
  },
  {
    id: "gev-004",
    geofenceId: "geo-003",
    locationName: "Lager Basel",
    userId: "user-003",
    userName: "Peter Keller",
    eventType: "enter",
    triggeredAt: "2026-03-19T07:00:00.000Z",
    autoAction: "checkin",
  },
  {
    id: "gev-005",
    geofenceId: "geo-003",
    locationName: "Lager Basel",
    userId: "user-003",
    userName: "Peter Keller",
    eventType: "exit",
    triggeredAt: "2026-03-19T16:30:00.000Z",
    autoAction: "checkout",
  },
  {
    id: "gev-006",
    geofenceId: "geo-001",
    locationName: "Lager Zürich",
    userId: "user-004",
    userName: "Lukas Meier",
    eventType: "enter",
    triggeredAt: "2026-03-19T07:45:00.000Z",
    autoAction: "checkin",
  },
  {
    id: "gev-007",
    geofenceId: "geo-002",
    locationName: "Lager Bern",
    userId: "user-002",
    userName: "Anna Brunner",
    eventType: "exit",
    triggeredAt: "2026-03-19T17:00:00.000Z",
    autoAction: null,
  },
  {
    id: "gev-008",
    geofenceId: "geo-004",
    locationName: "Lager Winterthur",
    userId: "demo-user-123",
    userName: "Max Muster",
    eventType: "enter",
    triggeredAt: "2026-03-18T09:00:00.000Z",
    autoAction: null,
  },
];

// ── BLE Beacons ──────────────────────────────────────────────────────────────

export const DEMO_BLE_BEACONS: BleBeacon[] = [
  {
    id: "beacon-001",
    name: "Beacon Lager Eingang",
    beaconUuid: "F7826DA6-4FA2-4E98-8024-BC5B71E0893E",
    major: 1,
    minor: 1,
    locationName: "Lager Zürich",
    entityType: "location",
    batteryLevel: 87,
    lastSeenAt: "2026-03-20T07:30:00.000Z",
    isActive: true,
  },
  {
    id: "beacon-002",
    name: "Beacon Werkstatt",
    beaconUuid: "F7826DA6-4FA2-4E98-8024-BC5B71E0893E",
    major: 1,
    minor: 2,
    locationName: "Lager Zürich",
    entityType: "location",
    batteryLevel: 42,
    lastSeenAt: "2026-03-20T06:55:00.000Z",
    isActive: true,
  },
  {
    id: "beacon-003",
    name: "Beacon Gabelstapler FM-X",
    beaconUuid: "A495DE00-C5B1-4B44-B512-1370F02D74DE",
    major: 2,
    minor: 18,
    locationName: "Lager Winterthur",
    entityType: "tool",
    batteryLevel: 15,
    lastSeenAt: "2026-03-19T16:00:00.000Z",
    isActive: true,
  },
  {
    id: "beacon-004",
    name: "Beacon Aussenlager Bern",
    beaconUuid: "E2C56DB5-DFFB-48D2-B060-D0F5A71096E0",
    major: 3,
    minor: 1,
    locationName: "Lager Bern",
    entityType: "location",
    batteryLevel: 93,
    lastSeenAt: "2026-03-20T08:10:00.000Z",
    isActive: true,
  },
  {
    id: "beacon-005",
    name: "Beacon Container Basel",
    beaconUuid: "E2C56DB5-DFFB-48D2-B060-D0F5A71096E0",
    major: 3,
    minor: 2,
    locationName: "Lager Basel",
    entityType: "location",
    batteryLevel: null,
    lastSeenAt: "2026-03-10T12:00:00.000Z",
    isActive: false,
  },
];

// ── Scan Result ───────────────────────────────────────────────────────────────

export const DEMO_SCAN_RESULT: ScanResult = {
  type: "material",
  item: {
    id: "mat-001",
    name: "Zement CEM II 42.5",
    number: "ZEM-001",
    unit: "Sack",
    quantity: 25,
    minQuantity: 20,
    locationId: "loc-001",
    locationName: "Lager Zürich",
    barcode: "7612345678901",
    notes: "Standardzement für Hochbau",
    createdAt: "2023-06-01T10:00:00.000Z",
    updatedAt: "2024-03-15T08:00:00.000Z",
  },
};
