export default {
  "karte": "Karten-Ansicht",
  "grundriss": "Grundriss-Ansicht",
  "dashboard-widgets": "Dashboard anpassen",
  "qr-self-service": "QR Self-Service",
  "multi-unternehmen": "Multi-Unternehmen",
  "branchen-vorlagen": "Branchen-Vorlagen",
  "command-palette": "Command Palette (Cmd+K)",
  "favoriten": "Favoriten & Zuletzt verwendet",
  "bulk-operationen": "Bulk-Operationen",
  "duplikat-erkennung": "Duplikat-Erkennung",
  "reservierungen": "Reservierungen",
  "materialanfragen": "Materialanfragen",
  "benachrichtigungen": "Benachrichtigungszentrale",
  "aktivitaetsprotokoll": "Aktivitätsprotokoll",
  "lieferschein-pdf": "Lieferschein PDF & Unterschrift",
  "tv-modus": "TV-Modus (Lager-Dashboard)",
  "barcode-generator": "Barcode-Generator",
  "foto-dokumentation": "Foto-Dokumentation",
  "zeiterfassung": "Zeiterfassung",
  "lieferverfolgung": "Lieferverfolgung",
  "garantieansprueche": "Garantieansprüche",
  "bestandsoptimierung": "Bestandsoptimierung",
  "externe-portale": "Externe Portale"
}
